service: inspec-serverless

provider:
  name: aws
  runtime: ruby2.5
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 256
  timeout: 30
  iamManagedPolicies:
    - 'arn:aws:iam::aws:policy/ReadOnlyAccess'
  environment:
    HOME: /tmp
    INSPEC_PROFILE: ${opt:inspec_profile}
    S3_DATA_BUCKET: ${opt:s3_data_bucket}

functions:
  inspec_scan:
    handler: handler.inspec_scan
    layers:
      - {Ref: InspecLambdaLayer }
  scheduled_inspec_scan:
    handler: handler.inspec_scan
    layers:
      - {Ref: InspecLambdaLayer}
    events:
    - schedule:
      rate: rate(10 minutes)
      enabled: true
      input:
        s3_bucket: ${opt:s3_data_bucket}
        inspec_profiles: ["https://github.com/martezr/serverless-inspec-profile"]
        stageParams:
          stage: ${opt:stage, 'dev'}

layers:
  inspec:
    path: layer
